### ISSUE TITLE
Question: i610T

### ISSUE THREAD

**Issue by DonaldTsang** [thanks4opensource/NotLinuxAjazzAK33RGB#2]
Does i610T from Ajazz uses the same firmware as AK33? I am looking for a 61 key keyboard that works better than RK61.

**Comment by thanks4opensource** [comment]
Sorry, I have no idea. The only Ajazz keyboards I've used are the two variants of the AK33 I describe in the README. My guess is that the i610T would be similar but not necessarily identical, but that's complete speculation.

**Comment by DonaldTsang** [comment]
Question: If I were to give you the money to purchase an i610T for research purposes would you accept it?

**Comment by thanks4opensource** [comment]
That's an interesting and generous offer. Thanks for putting it  forward.

I'm very busy right now with my other, more technical, GitHub open source projects, so any possibility of doing this would have to be at least a few weeks in the future. Note also that I wouldn't be able to guarantee any success at all -- the "inspirations" that allowed me to write NotLinuxAjazzAK33RGB might not strike again.

I also just checked more carefully online: The Ajazz i610T (which is not available from my normal sellers) has a monochrome backlight compared to RGB on the AK33. Is this correct? If so, its interface might be more different than I had speculated in my previous reply.

Do you have an i610T and if so have you used any software (I assume Windows) that came with it? What does the software do? Could you post one or more screenshots that show its capabilities? Also, what keyboard keys control it directly (without PC host intervention) and what do they do?

I looked at some of your GitHub repositories. Very impressive work. You seem to be a capable software developer. Not that I would ever do this, but have you considered running Ajazz's i610T Windows software and using a USB sniffer to look at what it's sending to and receiving from the keyboard? If you knew that you could easily modify  NotLinuxAjazzAK33RGB to do what you want. There are many USB sniffers available, both hardware and software, with both free and/or open source versions of the latter.

**Comment by DonaldTsang** [comment]
> That's an interesting and generous offer. Thanks for putting it forward.
> I'm very busy right now with my other, more technical, GitHub open source projects, so any possibility of doing this would have to be at least a few weeks in the future. Note also that I wouldn't be able to guarantee any success at all -- the "inspirations" that allowed me to write NotLinuxAjazzAK33RGB might not strike again.

Understandable, but I would like to start an FOSS initiative for my future EDC keyboard since https://github.com/pixeltris/GK6X/issues/12 isn't necessarily perfect for FOSS adoption, and I am looking forwards to seek alternatives that are cheap and good at the same time.

> I also just checked more carefully online: The Ajazz i610T (which is not available from my normal sellers) has a monochrome backlight compared to RGB on the AK33. Is this correct? If so, its interface might be more different than I had speculated in my previous reply.

Maybe the software are compatible like how GK6X series does it, but I am not completely sure.

> Do you have an i610T and if so have you used any software (I assume Windows) that came with it? What does the software do? Could you post one or more screenshots that show its capabilities? Also, what keyboard keys control it directly (without PC host intervention) and what do they do?
> I looked at some of your GitHub repositories. Very impressive work. You seem to be a capable software developer. Not that I would ever do this, but have you considered running Ajazz's i610T Windows software and using a USB sniffer to look at what it's sending to and receiving from the keyboard? If you knew that you could easily modify NotLinuxAjazzAK33RGB to do what you want. There are many USB sniffers available, both hardware and software, with both free and/or open source versions of the latter.

If there is a community of people looking for FOSS solutions of the keyboard then I would buy it and tinker with it ASAP since I would know that I would not walk alone... USB sniffers though are a head scratcher since I would expect this to be a Firmware flashing question regarding the software.

**Comment by thanks4opensource** [comment]
Interesting information. I took a quick look at pixeltris/GK6X and it seems to do a lot more than NotLinuxAjazzAK33RGB, which only attempts to control the RGB LEDs on the AK33. No key remapping, etc.

I think this repository's code does write to flash memory as the changes I've made using it survive power cycling the keyboard. But I don't know if I'd consider that "firmware flashing" as that implies rewriting the code that runs the keyboard. Maybe just a question of semantics. In any case, flashing firmware over USB requires sending data over USB, and a sniffer can show what that data is. Decoding it is another matter.

I'm not sure what you mean by your "future EDC keyboard" but there was mention in the pixeltris/GK6X posts of QMK. I don't know much about QMK but I have bought a  numeric keypad kit which uses a QMK-compatible microcontroller (haven't done anything with it yet, busy with other projects as per previous post). From the preliminary research I've done on QMK  it looks very good. I think if you want full control of your keyboard, and you're willing to build one from a kit (or from scratch) that would be the best way to go.

Finally, if you're using Linux or some other UNIX-lke OS with the X Window System, the `xmodmap` command allows remapping of any/all keyboard keys. I've been using it every day on dozens of different keyboards and hosts for over 20 years. It's not a "permanent" (doesn't change anything on the keyboard, needs to be run every time at login) nor cross-platform solution, but it might do what you need. (Apologies if you already know about xmodmap and have rejected it as non-applicable to your problem.)

**Comment by DonaldTsang** [comment]
> I'm not sure what you mean by your "future EDC keyboard"

I was referring to using the keyboard as a part of my daily life "Everyday Carry", otherwise good to ponder about alternatives regarding keyboards.

**Comment by thanks4opensource** [comment]
Thanks, now I understand. Hope you find a good solution for your keyboard requirements. Closing this issue -- feel free to reopen or file a new one if applicable to the this repository.
