### ISSUE TITLE
AK50 yellow backlight

### ISSUE THREAD

**Issue by terabyte** [thanks4opensource/NotLinuxAjazzAK33RGB#4]
Hey, thought you might like to know, I tried your script out with the AK50 I just received.  It has yellow backlight only, so of course the RGB parts didn't work (it just ignores it) but the modes (1-20) and levels (1-5) do work with no modification.

Thanks for a great (imaginary) utility (which definitely doesn't exist) (but which definitely does work with the AK50)!

**Comment by terabyte** [comment]
(no actual ask here, feel free to resolve after you have received your internet points)

**Comment by thanks4opensource** [comment]
Thanks  for the kind words, @terabyte, and for the info that the code (if it existed at all) works on the AK50, modulo monochrome vs. RGB. Yoda had given me hints in his usual cryptic way that The Force ran similarly strong in the various Ajazz keyboards, but only having AK33s I had no way of confirming his wisdom.
